# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2022'

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Staging Orchestrator TestSuite'
    testSet: 'UiBank Background Tests'
    folderName: 'Ionut Nicula'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Staging Orchestrator TestSuite'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Ionut Nicula'
    entryPoints: 'Main.xaml'
    